---
title: "manuscript figure 2"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE)
```

```{r}
library(bbnj)
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(here)
```

```{r clean & organize features}

#Read in csv of report from scenario 4
features <- readr::read_csv(here("../bbnj/inst/app/www/scenarios/s04a.biofish.alltime.mol50km_rep.csv"))

#Remove row with area of solution in km
features <- features[-c(1), ]

#Clean feature names

features$clean <- (gsub("^.*?p_","", features$feature)) 
features$clean <- (gsub("\\.n\\."," and ", features$clean))
features$clean <- (gsub("\\."," ", features$clean))

features$clean <- features$clean %>%
  str_replace_all(c(
  "bio_vgpm" = "Net Primary Production",
  "phys_vents" = "Hydrothermal Vents",
  "rls_all_now" = "Red List Sum Now",
  "rls_all_future" = "Red List Sum 2100",
  "phys_seamounts_gt200to800m" = "Seamounts >200-800m Summit Depth",
  "phys_seamounts_gt800m" = "Seamounts >800m Summit Depth",
  "phys_seamounts_0to200m" = "Seamounts 0-200m Summit Depth",
  "scapes_hetero" = "Benthic Habitat Heterogeneity"
    ))

simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}

features$clean <- sapply(features$clean, simpleCap)

#Add header row for species richness and species richness 2100

features<-rbind(features,c("Species Richness", NA, NA, "Species Richness",NA))
features<-rbind(features,c("Species Richness 2100", NA, NA, "Species Richness 2100",NA))

#Add ID column for custom reordering

features$id <- NA

#Add ID numbers for custom reordering

features$id[c(1,54,53,52,50,51,48,49,55,56)] <- c(1,2,3,4,5,6,7,8,9,33)
features$id[2:24]<-c(10:32)
features$id[25:47]<-c(34:56)

features <- features[order(features$id),]

#Since there are multiple x variables with same name (species richness for now & 2100) ggplot wants to plot those together. To get them to plot separately, create a copy of clean before merging clean and id. The graph is then plotted with clean + id and then the labels switched to clean.
features <- features %>% mutate(clean.label = clean,
              clean = paste(clean, id, sep = "_"))
              # clean = factor(clean, levels = clean)) 


# Convert relative_held to numeric
features$relative_held <- as.numeric(features$relative_held)

```

``` {r plot all features}
#Plot
ggplot(features,aes(x=reorder(clean,-id),y=relative_held,label=scales::percent(relative_held)))+
  geom_bar(stat="identity",width=0.5,fill="#91bfdb")+
  coord_flip()+
  scale_y_continuous(limits = c(0, 1),labels = scales::percent,expand = c(0,0))+
  scale_x_discrete(labels = rev(features$clean.label))+
  xlab("")+
  ylab("")+
  geom_text(colour="black",hjust = -0.4, size=3)+
  theme(
    axis.text.y = element_text(face=ifelse(features$clean %in% c("Pinnipeds_48","Pinnipeds_24"),"bold","plain")),
    plot.margin=unit(c(1,1,1,1),"cm")
  )



ggsave("figure2.png", width=6, height=9, units="in")

```

``` {r plot by group}

# Plot physical layers
physfeatures<-dplyr::filter(features, feature %in% c("phys_seamounts_gt200to800m", "phys_seamounts_gt800m","phys_seamounts_0to200m","phys_vents","bio_vgpm","scapes_hetero"))

ggplot(physfeatures,aes(x=reorder(clean,-id),y=relative_held,label=scales::percent(relative_held)))+
  geom_bar(stat="identity",width=0.5,fill="#91bfdb")+
  coord_flip()+
  scale_y_continuous(limits = c(0, 1),labels = scales::percent,expand = c(0,0))+
  scale_x_discrete(labels = rev(physfeatures$clean.label))+
  xlab("")+
  ylab("")+
  geom_text(colour="black",hjust = -0.4, size=3)


# Plot species richness (NOW) layers
nsppfeaturesnow<-features %>% 
  dplyr::filter(!(feature %in% c("phys_seamounts_gt200to800m", "phys_seamounts_gt800m","phys_seamounts_0to200m","phys_vents","bio_vgpm","scapes_hetero"))) %>% 
  dplyr::filter(!grepl("2100", feature), ) %>% 
  dplyr::filter(feature != "rls_all_future")

ggplot(nsppfeaturesnow,aes(x=reorder(clean,-id),y=relative_held,label=scales::percent(relative_held)))+
  geom_bar(stat="identity",width=0.5,fill="#91bfdb")+
  coord_flip()+
  scale_y_continuous(limits = c(0, 1),labels = scales::percent,expand = c(0,0))+
  scale_x_discrete(labels = rev(nsppfeaturesnow$clean.label))+
  xlab("")+
  ylab("")+
  geom_text(colour="black",hjust = -0.4, size=3)

# Plot species richness (2100) layers
nsppfeatures2100<-features %>% 
  dplyr::filter(!(feature %in% c("phys_seamounts_gt200to800m", "phys_seamounts_gt800m","phys_seamounts_0to200m","phys_vents","bio_vgpm","scapes_hetero"))) %>% 
  dplyr::filter(grepl("2100", feature), ) %>% 
  dplyr::filter(feature != "rls_all_now")

ggplot(nsppfeatures2100,aes(x=reorder(clean,-id),y=relative_held,label=scales::percent(relative_held)))+
  geom_bar(stat="identity",width=0.5,fill="#91bfdb")+
  coord_flip()+
  scale_y_continuous(limits = c(0, 1),labels = scales::percent,expand = c(0,0))+
  scale_x_discrete(labels = rev(nsppfeatures2100$clean.label))+
  xlab("")+
  ylab("")+
  geom_text(colour="black",hjust = -0.4, size=3)


```
