---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F)
```

```{r}
library(tidyverse)
library(glue)
library(here)
library(raster)
library(knitr)
library(bbnj)
library(sf)
library(RColorBrewer)
library(magick)
#devtools::load_all() # devtools::install_local(force=T)
select = dplyr::select
```



```{r}
  r1 <- raster(here("../bbnj/inst/app/www/scenarios/s04a.biofish.alltime.mol50km_sol.tif"))
  r2 <- raster(here("../bbnj/inst/app/www/scenarios/s02a.bio.alltime.mol50km_sol.tif"))

  rng1 <- c(cellStats(r1, "min"), cellStats(r1, "max"))
  rng2 <- c(cellStats(r2, "min"), cellStats(r2, "max"))
  stopifnot(identical(rng1, c(0,1)))
  stopifnot(identical(rng2, c(0,1)))

  r_d  <- r2*10 - r1
  # plot(r_d, main="r_d")
  # table(values(r_d), useNA = "ifany")

  d_subs <- tribble(
    ~old,   ~new,
    0, -9999,
    9,     1,
    -1,    1,
    10,     -1)

  r_ds <- subs(r_d, d_subs, "old", "new")
  # table(values(r_ds), useNA = "ifany")
  # plot(r_ds, main="r_ds")
  r_dsm <- mask(r_ds, r_ds, maskvalue=-9999)
  # table(values(r_dsm), useNA = "ifany")
  # plot(r_dsm, main="r_dsm")

  #plot(r_dsm)
  
  writeRaster(r_dsm, "pewglossymap/s04-s02a.tif")

  
# Create shapefile
  
  p_dsm<-rasterToPolygons(r_dsm) %>%
    st_as_sf()
  
  #plot(p_dsm)
  
  write_sf(p_dsm, "pewglossymap/s04-s02a.shp")
  
  
# Create png
  
png<- ("pewglossymap/s04-s02a.png")
  # overlays
  countries  <- rnaturalearth::ne_countries(returnclass = "sf") %>%
    st_transform(54009)
  graticules <- st_graticule(countries)

  png(png, width=480*4, height = 480*4, res=300, type="cairo", units='px')
  plot(r_dsm, legend=F, axes=F, box=F, col=c("#E41A1C","#4DAF4A"))
  plot( st_geometry(countries), add=T, col=gray(0.8), border=gray(0.7), lwd=0.5)
  plot(st_geometry(graticules), add=T, col=gray(0.6), lwd=0.5)
  dev.off()

  png %>%
    magick::image_read() %>%
    magick::image_trim() %>%
    magick::image_write(png)
  
  
```
